### ISSUE TITLE
Page Recherche : manque un champ pour "nom entreprise"

### ISSUE THREAD

**Issue by mrn-i** [dataforgoodfr/batch7_rse#18]
Pour assurer la fonction de recherche dans les DPEF, on propose des options de filtre sur :
* le terme à rechercher (texte, obligatoire)
* le nom de l'entreprise (texte, option, default = tous les noms)
* la période (choix, option, default = toutes les DPEFs)
* les secteurs (checkboxes, option, default = tous les secteurs) 

Or le formulaire  Searchform (dans forms.py) comporte 1 seul champ de texte hérité de BasicSearchForm. 

Peux-tu créer un 2éme champ de texte pour le nom de l'entreprise ? (je suppose que dupliquer 2 fois le même champ sur la page va poser problème  ^^)

**Comment by CharlesGaydon** [comment]
Ce problème semble corrigé:
![image](https://user-images.githubusercontent.com/11660435/83658494-91686d80-a5c2-11ea-9cfe-9e8ef4800811.png)
