### ISSUE TITLE
Page BDD Entreprises : barre de recherche

### ISSUE THREAD

**Issue by mrn-i** [dataforgoodfr/batch7_rse#19]
Pour voir les entreprises et rechercher des DPEF, on parlait de faire une barre de recherche sur :
* le nom de l'entreprise (texte, option, default = tous les noms)
* la période (choix, option, default = toutes les DPEFs)
* les secteurs (checkboxes, option, default = tous les secteurs) 

Pour l'instant la page "company_list.html" n'inclue pas de formulaire de recherche. Peut-on utiliser le SearchForm ou faut-il un formulaire spécifique, voir un autre système ? (Je pensais à un système de filtre qui vient seulement updater la vue de la liste sans passer par le backend, mais je ne sais pas comment faire un truc comme ça).

**Comment by CharlesGaydon** [comment]
![image](https://user-images.githubusercontent.com/11660435/83894356-7a0bba80-a751-11ea-91cf-24c995dfbe7b.png)
Ca semble pris en compte maintenant !
