### ISSUE TITLE
Alléger le répertoire en excluant la base de données de DPEFs

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#2]
Le dossier src/webapp/data/DPEFs qui contient les DPEFs fait 150M, et ce pour seulement une quinzaine de DPEFs actuellement.
On risque potentiellement d'avoir un clonage très lourds lorsque la base de donnée sera complète (>1.4G) ce qui pas forcément idéal pour un outil de versionnement comme git ; ca rend en plus les clonage fastidieux.

Je suggère que la base de données des DPEFs pourrait être stockées sous forme d'archive et hébergée hrs de git, si on trouve le lieu adapté pour cela. Et il suffirait d'un script python pour la télécharger par API.

Les DPEFs étant également conservées dans l'historique git, leur dossier pourra être supprimé de l'historique avec une commande [de ce type](https://myopswork.com/how-remove-files-completely-from-git-repository-history-47ed3e0c4c35).

@Renaud-D-Harreville Est-ce que ça poserait problème en termes de bases de données ?

Il faudrait déjà être sûr qu'un lieu d'hébergement existe.
Puis le process d'installation pourrait être:

- git cloner le projet
- télécharger les données depuis l'hébergeur externe à github
- lancer un script de peuplement de la base
- lancer le site web

**Comment by Renaud-D-Harreville** [comment]
Pour répondre en deux parties à ton questionnement, je suis d'accord qu'il faudrait virer les PDFs du github, je ne sais pas trop si c'est leur place. En revanche, je ne sais pas trop quel serait / devrait être la bonne solution pour récupérer les PDFs. La pluspart des projets que tu trouves sur internet fournissent via leurs projets Github une application 'nue', sans les données. C'est en général à l'utilisateur de récupérer ces données. 
Je ne sais pas trop pour le moment quel serait la meilleure solution sachant que nous avons en réalité assez peu de temps encore devant nous. Peut-être comme tu dis un lien quelque part sur internet pour récupérer ces données. Ou alors, directement via le site web ? En soit les PDFs et toutes les informations seront à disposition :)

**Comment by CharlesGaydon** [comment]
Directement via le site web c'est une solution qui paraît assez maligne en fait.
En gros le lien exposé pour le téléchargement de la base (une grosse archive) est le même que celui qui sert à reproduire le projet ailleurs...
Je vois un problème à ça : si le serveur a un soucis, on risque de perdre la base de données; est-ce qu'on serait pas plus rassuré si cette base était sur un service de data existant ?

**Comment by Renaud-D-Harreville** [comment]
> Je vois un problème à ça : si le serveur a un soucis, on risque de perdre la base de données; est-ce qu'on serait pas plus rassuré si cette base était sur un service de data existant ?


Si j'avoue que ce serait embêtant de tout perdre comme ça...

Il faudrait voir ou est ce que l'on peut mettre ces données à disposition alors. Peut-être demander soit au gouvernement, soit à DataForGood, de mettre un espace de stockage à disposition. 

On pourra mettre un lien sur le github qui redirige vers ce service avec une petite notice pour importer les données.

**Comment by CharlesGaydon** [comment]
On n'aura ni resource du ministère, ni ressource supplémentaires de D4G, à moins de migrer une partie du système sur AWS.
A terme stocker les DPEFs dans le répo n'est pas tenable : on aura au moins 150 * 10Mo (sur la base du poids des 14 pdfs actuels d'environ 10 Mo)...  Github recommande de garder les répo sous 1Go pour éviter des soucis de performances.
A mon avis un stockage sur le serveur actuel c'est quand même risqué car ça rend les sources dépendantes de l'implémentations du site... Je vais chercher si il existe des services de ce type plus durable.

**Comment by CharlesGaydon** [comment]
Bon il y a des solutions, mais ça risque d'ajouter une couche de complexité non nécessaire.
Le mieux c'est qu'on fasse une archive zip contenant;
- le csv de métadonnées ([companies_metadata.csv](https://github.com/dataforgoodfr/batch7_rse/blob/master/webapp/data/model/Companies/companies_metadata.csv)) 
- les PDFs dans des dossiers par secteur.

Cette archive pourra être stockées dans le serveur, et téléchargeable en ligne de commande (curl).
Une méthode très simple semble être d(utiliser Node.js : 
https://stackoverflow.com/a/16350826/8086033

**Comment by CharlesGaydon** [comment]
@Renaud-D-Harreville Qu'est-ce que tu en penses ?
J'ai crée une archive au bon format, pour quand tu pourra tester cette dernière approche. Je peux te la transférer quand nécessaire.

**Comment by CharlesGaydon** [comment]
La base globale n'ira pas dans le repo. On garde la 15 de pdf cependant.
