### ISSUE TITLE
Chargement double du modèle à l'initialisation du server

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#23]
La commande 
`python manage.py runserver`
lance deux fois le chargement du modèle de vectorisation.

![image](https://user-images.githubusercontent.com/11660435/82057492-b0f72f00-96c3-11ea-9513-a1fbd660e324.png)

**Comment by CharlesGaydon** [comment]
Explication:
`runserver` est lancé à deux reprises, dans deux processus différents : l'un prcesse les requêtes, et l'autre permet l'_auto-reloading_, la mise à jour du serveur lorsque le code source est modifié.
C'est utile seulement en phase de développement, lorsque l'on travaille sur du code css/html ou django par exemple. 
@mrn-i Tu as du le remarquer en développant le design ?

Pour éviter que cela arrive lorsque l'on veut simplement tester que le site est opérationnel, faire:
`python manage.py runserver --noreload `

**Comment by mrn-i** [comment]
Pour préciser, modifier le css ou le html ne reload pas le process (en tout
cas pycharm est configuré par défaut pour ça). Il suffit de recharger la
page dans le browser pour voir la modif.
Le reload intervient dès qu'on vient toucher au .py : un changement de
caractere dans les forms, views ou url et c'est parti. Très vite lourd
quand on bosse sur les formulaires :D
Merci pour l'astuce !

Le mer. 20 mai 2020 à 18:08, Charles Gaydon <notifications@github.com> a
écrit :
