### ISSUE TITLE
Page d'accueil: Pimper et ajouter le texte

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#32]
Cf. visuel plus bas.
Il y a en vrc:
- Corriger le titre, point d'exclamation
- Un call to action avant la searchbar ("rentrez une requetes et appuyez sur entrée"
- trois petit points à fin de l'exemple de la searchbar 
- un exemple qui change à chaque reload
- rajouter plus d'espace entre les différents éléments
- Un encadré expliquant ce que sont les DPEFs
![image](https://user-images.githubusercontent.com/11660435/83255927-ad7aa200-a1b1-11ea-80e1-141a69a7ce7f.png)

**Comment by mrn-i** [comment]
- [x] Corriger le titre, point d'exclamation

- [x] Un call to action avant la searchbar ("rentrez une requetes et appuyez sur entrée"

- [x] trois petit points à fin de l'exemple de la searchbar

- [ ] un exemple qui change à chaque reload
_Très bonne idée ! Pas sûre de trouver comment faire, il faut que je fasse quelques essais avec les formulaires_

- [x] rajouter plus d'espace entre les différents éléments

- [x]  Un encadré expliquant ce que sont les DPEFs

**Comment by CharlesGaydon** [comment]
Closing, le dernier point étant un peu gadget :)
