### ISSUE TITLE
Pied de page:  Pimper + remplir de texte

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#34]
Aspects actuel du pied de page:
![image](https://user-images.githubusercontent.com/11660435/83256597-fda63400-a1b2-11ea-9d4f-26d8c270753e.png)

Idées:
- A gauche, "Une collaboration [logo MTES] et [logo D4G]
- A droite: "Une question ? Une remarque ? Contactez-nous sur Github [logo github].

**Comment by mrn-i** [comment]
- [x] A gauche, "Une collaboration [logo MTES] et [logo D4G]

- [x] A droite: "Une question ? Une remarque ? Contactez-nous sur Github [logo github].

**Comment by mrn-i** [comment]
OK dans ma dernière pull request
