### ISSUE TITLE
Page "Liste des DPEFs": pimper et remplir

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#35]
- [ ] Renommer ("Recherche de DPEFs")
- [x] Mettre un titre à la page en haut du style "Base de données de Déclarations de Performances Extra-Financières
- [x]  Mettre un petit texte de call to action disant combien il y a de DPEFs, de secteurs et actuellement: `Rechercher un DPEF parmi N documents appartenants à N entreprises réparties en N secteurs : `
- [x] Placer la searchbar au dessus des résultats (cf. nouvelle searchbar de @mrn-i ? :)  )
- [ ] Encadrer le tableau des résultats pour qu'il soit plus joli ?
- [x] Mettre un exemple dans la barre de recherche 
- [x] Mettre des titres à chaque colonne du tableau
- [ ] Permettre le téléchargement de chaque DPEFs depuis cette page
- [x] Ne pas afficher les chemins locaux complet (`polls/models/dpef/edf_2018_debug.pdf`) des DPEFs, seulement le nom du fichier (`edf_2018_debug.pdf`)

**Comment by mrn-i** [comment]
- [ ]  Renommer ("Recherche de DPEFs")
_Yes je reprends navbar et footer demain_

- [ ]  Encadrer le tableau des résultats pour qu'il soit plus joli ?
_Je vais faire des essais ^^_

- [x]   Mettre des titres à chaque colonne du tableau
_Je pense que ça alourdit inutilement la page, on comprends très bien le contenu sans les headers_

 - [ ]   Permettre le téléchargement de chaque DPEFs depuis cette page
 - [x]   Ne pas afficher les chemins locaux complet (polls/models/dpef/edf_2018_debug.pdf) des DPEFs,
_@Renaud-D-Harreville besoin de toi pour ces deux-là_

**Comment by CharlesGaydon** [comment]
> * [ ]   Renommer ("Recherche de DPEFs")
>   _Yes je reprends navbar et footer demain_
> * [ ]   Encadrer le tableau des résultats pour qu'il soit plus joli ?
>   _Je vais faire des essais ^^_
> * [ ]    Mettre des titres à chaque colonne du tableau
>   _Je pense que ça alourdit inutilement la page, on comprends très bien le contenu sans les headers_
> * [ ]    Permettre le téléchargement de chaque DPEFs depuis cette page
> * [x]    Ne pas afficher les chemins locaux complet (polls/models/dpef/edf_2018_debug.pdf) des DPEFs,
>   _@Renaud-D-Harreville besoin de toi pour ces deux-là_

J'ai fait quelqu'uns des points. Je n'avais pas vu ton commentaire désolé, et ai quand même mis des titres pour avoir le même design de tableau que pour la recherche thématique.

**Comment by CharlesGaydon** [comment]
Le téléchargement des PDFs est un sujet assez complexe en fait, donc j'ai crée une issue séparée:
https://github.com/dataforgoodfr/batch7_rse/issues/48
@mrn-i Je ferme cette issue, n'hésites pas à la rouvrir si tu juges que certains sujets sont encore sur la table.
