### ISSUE TITLE
Page "Recherche Thématique": pimper et compléter

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#36]
- [x] Mettre un exemple dans la searbar avec plusieurs mots pour illustrer que c'est possible style `Action lutte pollution marine`
- [x] Ajouter call to action du style `Effectuez une recherche par mot clef parmi N extraits issus de N DPEFs appartenants à N entreprises réparties en N secteurs :`
- [x] Mettre période par défaut 2018 - 2019 pour éviter le blanc
- [x] Ajouter des titres aux colonnes du tableau de résultats  `Extrait` , `Match`
- [x] Arrondir le score de proximité et le mettre en %
Mettre les autres données:
- [ ] Rajouter trois petits points avant et après l'extrait pour bien dire que c'est un extrait (?) P.ex.

> ...] Le concours invitait les participants à devenir des « bâtisseurs de solutions innovantes » à partir de trois thématiques phares : le mieux-vivre ensemble, les nouveaux services et les nouvelles technologies. [...

Ou alors mettre le paragraphe de contexte drectement, et le match en gras dedans pour éviter la redondance.

> Le challenge Immo-Inno : un concours interne pour inventer les logements de demain Plus de 300 collaborateurs se sont mobilisés pour participer à Immo-Inno, le premier concours d’innovations organisé par Eiffage Immobilier et Eiffage Construction sur le thème du logement de demain. **Le concours invitait les participants à devenir des « bâtisseurs de solutions innovantes » à partir de trois thématiques phares : le mieux-vivre ensemble, les nouveaux services et les nouvelles technologies.** Origami, le projet vainqueur, propose une gamme d’appartements ultra-compacts offrant autant de fonctionnalités que des appartements de plus grande taille. Immo Éco, un projet de résidence à charges minimales, s’est imposé en deuxième position, suivi par Fablife, également élu Coup de cœur du public. Ce dernier projet vise à accompagner les nouveaux propriétaires dans les démarches liées à leur achat, du choix du déménageur jusqu’aux petits travaux d’installation. Ces trois projets font l’objet d’expérimentations en 2018 sur des chantiers en Île-de-France, notamment à Châtenay-Malabry.

Eventuellement: ne garder que l'extrait et afficher le paragraphe avec l'extrait en gras après survol de la phrase:

> ...] Le concours invitait les participants à devenir des « bâtisseurs de solutions innovantes » à partir de trois thématiques phares : le mieux-vivre ensemble, les nouveaux services et les nouvelles technologies. [...

**Comment by mrn-i** [comment]
@Renaud-D-Harreville J'attends que le search btn soit fonctionnel pour pimper l'affichage du résultat :) poke moi quand c'est bon

**Comment by CharlesGaydon** [comment]
@mrn-i Je te poke, car la barre fonctionne :) 
PS: Actuellement le seul élément qui en fonctionne pas sur cette page c'est le filtre de secteur, cf. https://github.com/dataforgoodfr/batch7_rse/issues/33, mais ce sera rapide à faire :)

**Comment by CharlesGaydon** [comment]
SI jamais tu veux tenter la méthode par survol de l'extrait, l'argument css (il me semble, mais il est aussi utilisable en javascript) est `onmouseover`

https://stackoverflow.com/questions/17354655/mouse-over-in-a-django-template

**Comment by CharlesGaydon** [comment]
Lié à https://github.com/dataforgoodfr/batch7_rse/issues/44
