### ISSUE TITLE
Peupler la BDD automatiquement directement depuis un DPEF

### ISSUE THREAD

**Issue by Renaud-D-Harreville** [dataforgoodfr/batch7_rse#4]
Afin de faciliter l'import de données à la fois dans la base de données et à terme directement dans le modèle NLP, il serait interressant de rajouter une fonctionnalité permettant, à partir d'un DPEF, d'extraire les phrases contenues dedans ainsi que leurs principales meta données correspondantes [(classe Sentence de ce fichier)](https://github.com/dataforgoodfr/batch7_rse/blob/master/src/webapp/polls/models.py) 
- le texte de la phrase
- la page (de départ si sur plusieurs pages)
- son contexte (paragraphe contenant)
- si possible, son vecteur

Cette fonctionnalité permettrait de remplir la base de données de plusieurs manières : 

- A la volée via un formulaire associé (pourrait être désactivé si necessaire).
- A partir d'un dossier contenant l'ensemble des documents DPEFs (nommés <nom_entreprise>_<année>_*.pdf)

Cela pourrait résoudre donc en partie la problématique de #2 en facilitant l'import des données. 

De plus, il doit être envisageable si je ne me trompe pas de pouvoir compéter le modèle NLP à partir de ces nouvelles données  (phrases) ? Cela permettrait donc aussi de faciliter la mise à jour du modèle NLP.

@CharlesGaydon Sais tu si cela est faisable relativement facilement ? Il faudrait une fonction qui prenne en paramètre un chemin de fichier d'un DPEF et qui renvoie une liste de phrases avec leurs méta-données (dont vecteur si possible, bien que cela est faisable après coup ).

De mon côté, je vais m'occuper de la partie permettant, à partir d'un document DPEF de parser son nom de fichier pour obtenir le nom de son entreprise ainsi que son année afin de pouvoir correctement ajouter l'ensemble en BDD.

**Comment by CharlesGaydon** [comment]
Tout d'abord: "De mon côté, je vais m'occuper de la partie permettant, à partir d'un document DPEF de parser son nom de fichier pour obtenir le nom de son entreprise ainsi que son année"

--> l'ajout du secteur est déjà faite, par ce commit: https://github.com/dataforgoodfr/batch7_rse/commit/35dae124d40d9c3dffb940f73a3b423b347614f7 
L'ajout de l'année peut se faire très facilement, au même endroit, depuis l'objet Path qui contient le chemin du fichier considéré, dans la fonction https://github.com/dataforgoodfr/batch7_rse/blob/851db80bff15a87686b0cd5ab485ecd5111e2986/src/webapp/polls/rse_model/rse_watch/pdf_parser.py#L343

**Comment by CharlesGaydon** [comment]
> Il faudrait une fonction qui prenne en paramètre un chemin de fichier d'un DPEF et qui renvoie une liste de phrases avec leurs méta-données (dont vecteur si possible, bien que cela est faisable après coup )

C'est tout a fait faisable, et j'attendais qu'on avance assez sur la base de donnée pour y arriver. 
Actuellement le code est conçu ainsi : pdf_parser.py lance deux fonctions: 
https://github.com/dataforgoodfr/batch7_rse/blob/851db80bff15a87686b0cd5ab485ecd5111e2986/src/webapp/polls/rse_model/rse_watch/pdf_parser.py#L373
et
https://github.com/dataforgoodfr/batch7_rse/blob/851db80bff15a87686b0cd5ab485ecd5111e2986/src/webapp/polls/rse_model/rse_watch/sententizer.py#L66
Ce sont des fonctions qui chacune produisent un csv. 
Dans chacune de ces fonctions, on prends toutes les données, et on parallelise une transformation pdf -> paragraphe pour l'une, et paragraphe -> sentence pour l'autre.

Ce qu'on peut assez facilement faire ce serait intégrer les deux fonctions en une seule, **_à l'échelle du pdf_**.  Pour ensuite paralléliser cette fonction qui ferait pdf -> (... ) -> sentences.

Concrètement on aurait:

```
def parse_dpef(input_file: pathlib.Path, dict_annotations: dict):
   # cree le pandas DF contenant une ligne par phrase + metadonnées
   # parcourt le DF pour l'intégrer à la base SQL
```
(dict_annotations est une version dictionnaire de entreprises.csv qui donne les pages que l'on veut parser (i.e. rse_ranges).
Et on pourrait paralléliser le lancement de ces fonctions. Il faudra juste qu'il n'y ai pas de soucis d'accès concurrent à la base sql.

**Comment by CharlesGaydon** [comment]
> (dont vecteur si possible, bien que cela est faisable après coup )

Le vecteur dépend de la base de donnée entière. Et dans ce cas doit être recalculé lorsque la base de donnée est aussi complète que possible. On ne peut donc pas l'intégrer directement à la phase d'intégration de nouveau(x) pdf dans la base : il faut une fonction supplémentaire à appeler après, une fois la base "complète".
Ca peut être quelque chose comme:

> def vectorize_all_sentences():
>     # recompute the NLP model on all sentences
>     # for each sentence in sql database, calculate the vector and update it in the database

**Comment by CharlesGaydon** [comment]
J'ai ajouté l'année au parsing dans https://github.com/dataforgoodfr/batch7_rse/commit/65b185e57049114da912d5cac6b60c3d80bad82b

**Comment by Renaud-D-Harreville** [comment]
> Le vecteur dépend de la base de donnée entière. Et dans ce cas doit être recalculé lorsque la base de donnée est aussi complète que possible. On ne peut donc pas l'intégrer directement à la phase d'intégration de nouveau(x) pdf dans la base : il faut une fonction supplémentaire à appeler après, une fois la base "complète".
Ca peut être quelque chose comme:

    def vectorize_all_sentences():
    # recompute the NLP model on all sentences
    # for each sentence in sql database, calculate the vector and update it in the database

C'est d'accord, je pense que c'est effectivement la bonne solution. Il faut donc aussi que je fasse en sorte de séparer l'import des données brutes, de la partie mise à jour du modèle (Je vais créer une issue dédiée en temps voulu). 
On est donc d'accord qu'il faut en premier lieu populariser la BDD avec les phrases, sans compléter tout de suite le vecteur associé ?

**Comment by Renaud-D-Harreville** [comment]
> C'est tout a fait faisable, et j'attendais qu'on avance assez sur la base de donnée pour y arriver.
Actuellement le code est conçu ainsi : pdf_parser.py lance deux fonctions:

Ok, je vais regarder ça plus en détail pour créer la méthode que tu proposes.

Je pense cependant diviser cette partie 

```
def parse_dpef(input_file: pathlib.Path, dict_annotations: dict):
   # cree le pandas DF contenant une ligne par phrase + metadonnées
   # parcourt le DF pour l'intégrer à la base `SQL`
```

en quelque chose comme :
 
```
def parse_dpef(input_file: pathlib.Path, dict_annotations: dict):
   # cree le pandas DF contenant une ligne par phrase + metadonnées
  return pandas.DataFrame

def to_sentences(dataframe: pd.DataFrame, dict_annotations):
  # Create models.Sentence objects from the dataframe and the dict_annotaions infos
  # yield list(models.Sentences)

def import_sentences(filepath):
  df = parse_dpef(...)
  for sentence in to_sentences(...)
    sentence.save()
```

Cela permet de mieux séparer chacune des tâches, et de rendre le code plus réutilisable.

Pour la partie parallélisation, je ne sais pas encore trop dans quelle mesure ce sera possible avec Django. Il faudra y réfléchir. De même je pense que cela méritera une issue dédiée si cela nous pose problème quand nous y serons.

**Comment by CharlesGaydon** [comment]
> On est donc d'accord qu'il faut en premier lieu populariser la BDD avec les phrases, sans compléter tout de suite le vecteur associé ?
Oui

**Comment by CharlesGaydon** [comment]
> Cela permet de mieux séparer chacune des tâches, et de rendre le code plus réutilisable.

Oui je suis ok avec cette séparation parsing - transformation en objet Django - population de la BDD.
A mon avis, c'est donc import_sentence qui pourra être parallélisé.
Ca semble possible, d'après https://stackoverflow.com/a/10684672/8086033, de paralléliser une tâche django : il suffit de laisser chaque worker recréer sa propre connexion à la BDD.

**Comment by CharlesGaydon** [comment]
Note que cette méthode doit aussi pouvoir être utilisée pour paralléliser la vectorisation des phrases :)

**Comment by CharlesGaydon** [comment]
La méthode PDF -> sentence dataframe a été créee dans pdf_parser.py  cf. #9.
Elle a finalement pour signature:
`get_sentences_dataframe_from_pdf(config, dpef_path)`

**Comment by CharlesGaydon** [comment]
@Renaud-D-Harreville Gentle bump :) Est-ce que cette fonction répond à ta demande ?

> il serait interressant de rajouter une fonctionnalité permettant, à partir d'un DPEF, d'extraire les phrases contenues dedans ainsi que leurs principales meta données correspondantes (classe Sentence de ce fichier)

Si oui on doit pouvoir fermer cette issue :)

**Comment by CharlesGaydon** [comment]
https://github.com/dataforgoodfr/batch7_rse/pull/26
