### ISSUE TITLE
[Searchbar] Mise en valeur des mots ayant le plus porté le match

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#44]
![image](https://user-images.githubusercontent.com/11660435/83941492-197d8b80-a7ec-11ea-8270-6bf06e1c5900.png)

Idée:
- Surligner les n mots les plus proches chacun d'un des n mots de la requête d'entrée pour comprendre le match.

**Comment by CharlesGaydon** [comment]
Il y a une difficulté: faire le lien entre la phrase de la BDD, le modèle qui est appelé sur toutes les phrases, et le html + css. Ce sont pas mal d'effort pour une mise en valeur qui est surement importante pour mieux comprendre pourquoi il y a eu un match.

Niveau model: il faudra commencer par sortir une liste restreinte de mots "importants" avec éventuellement leur poids BM25

Niveau design: il faudra commencer par simplement permettre l

**Comment by mrn-i** [comment]
J'ai trouvé comment surligner :)  reste plus qu'à rendre accessible dans le contexte la liste mots "importants".
Pour l'instant ça surligne juste les mots de la liste statique "impact environnemental carbone climat ressources"

**Comment by CharlesGaydon** [comment]
C'est top ! 
Je vais commencer à développer quelque chose alors, pour voir si on peut mettre en valeurs certains éléments.
Si je comprend bien tu applique une fonction sur le texte de la phrase, en lui ajoutant des balises ? Est-ce que tu as vu si il existait des "niveau" de highlight ou si c'était binaire highlighté/pas highlighté ? Que je ne m'embête pas à sortir des poids à différents mots si on ne peut pas les visualiser après.

**Comment by mrn-i** [comment]
Pour l'instant la fonction est binaire (highlight/Pas highlight) mais ça
peut s'adapter. Regarde comment c'est fait dans filters.py, on peut
rajouter des conditions sur le score et définir 3 niveaux de jaune par
exemple :)

 essaye de garder les score si c'est possible du coup !

**Comment by mrn-i** [comment]
A quoi ressemblerait la liste à la fin ?
Je vais faire des tests de highlight avec une liste de tuple (mot,poids)

**Comment by mrn-i** [comment]
Mon dernier commit permet d'ajuster le highlight des mots selon leur score :)
 @CharlesGaydon ta fonction doit renvoyer une liste sous cette forme : [("mot", poids)]
ex :  [("impact",35),("environnemental",52),("carbone",65),("climat",58),("ressources",8)]
Chargée dans le context de la page.

**Comment by CharlesGaydon** [comment]
Top, avec un score entre 0 e 100 si je comprends bien alors ? 
J'espère avoir l'occasion d'implémenter cette fonctionnalité. En ce moment la priorité est Heroku + BDD, mais une fois ces soucis gérés... je m'en occuperai.

**Comment by CharlesGaydon** [comment]
3 plus proche mots au dessus de 50% de similarité et les mots de la query si présent, avec niveaux de transparence.
