### ISSUE TITLE
Remonter webapp dans l'arborescence

### ISSUE THREAD

**Issue by CharlesGaydon** [dataforgoodfr/batch7_rse#5]
Maintenant que toutes les source pythons de parsing/NLP ont été déplacée dans webapp/polls/rse_model, le dossier src ne contient que le dossier webapp.

Le dossier webapp peut être remonté d'un cran pour avoir une arborescence moins profonde.
Coté scripts python ça ne posera pas de problème car les chemins de configuration sont relatifs. 
Si ça doit impacter des configurations  de docker/django, je préfère laisser la main dessus.

**Comment by Renaud-D-Harreville** [comment]
J'ai remonté le dossier webapp comme demandé (Visible sur [ce commit](https://github.com/dataforgoodfr/batch7_rse/tree/85884ce8304bc46303e48ecb653ac54315f596c0))
Dis moi si cela te correspond, tu pourras fermer l'issue si ça te va.

J'en ai aussi profiter pour nettoyer un peu les dossiers 'data' que j'avais créés. 
Désormais, je mettrais toutes les données de django dans le dossier webapp/data. Avec à l'intérieur un dossier par application (donc polls dans notre cas). 
J'ai supprimé aussi en BDD l'ensemble des données dans les tables, afin que l'on puisse reconstruire une BDD de test plus interressante. Je vais m'ouvrir une issue pour ce besoin précis.

**Comment by CharlesGaydon** [comment]
Niquel, ça rend le dossier plus lisible.
