### ISSUE TITLE
Voir pour retirer pywin32, lié à windows

### ISSUE THREAD

**Issue by Renaud-D-Harreville** [dataforgoodfr/batch7_rse#6]
En utilisant la commande `pip install -r requirements.txt` on tombe sur cette erreur : 

```
ERROR: Could not find a version that satisfies the requirement pywin32==227 (from -r requirements.txt (line 54)) (from versions: none)
ERROR: No matching distribution found for pywin32==227 (from -r requirements.txt (line 54))
```
En regardant [ici](https://wiki.python.org/moin/PyWin32), il semble que ce soit un module dédié à windows. Il faut donc le retirer pour être multi-plateforme. 
En faisant une recherche sur le mot 'pywin32' dans notre projet, je ne le trouve que dans requirements.txt. Peut-être n'est-il tout simplement plus utile ?

**Comment by Renaud-D-Harreville** [comment]
D'autre part, ce sera un élément bloquant pour l'ajout des dépendances dans le docker. En effet, lors de l'import des dépendances via la commande `pip install -r requirements.txt`, si celle-ci renvoie une erreur, la construction (build) du docker ne pourra se faire correctement.

**Comment by Renaud-D-Harreville** [comment]
A priori il y a une autre dépendance : `pywinpty` qu'il faut ausi retirer. Est-ce possible de regarder cela aussi ?
Pour le coup, je ne sais pas à quoi ça sert cette dépendance : [https://pypi.org/project/pywinpty/](https://pypi.org/project/pywinpty/)

**Comment by Renaud-D-Harreville** [comment]
Ah si, c'est un binding python de [cette librairire](https://github.com/rprichard/winpty)

**Comment by CharlesGaydon** [comment]
Tu peux supprimer. 
Récemment j'ai migré mon setup de programmation vers mon ordi perso ; j'ai utilisé le PowerShell et chocolatey pour installer python, et je suis passé à [virtualenvwrapper-win](https://pypi.org/project/virtualenvwrapper-win/) (une version de virtualenvwrapper portée vers windows) pour éviter d'être dépendant des environnements conda sur ce projet.

Les packages que tu cite sont probablement une dépendance de virtualenvwrapper-win, mais elle n'est pas nécessaire pour le projet.

**Comment by CharlesGaydon** [comment]
N'hésite pas à rouvrir cette issue si ça cause des soucis.
